spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doctor
    username: postgres
    password: new_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: DoctorS.Med.Fazo@gmail.com
    password: taub optv rywl bgol
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    iPAndPort: http://localhost:8081/
    conformEmailForSignUpURL: api/v1/auth/verify/
    conformEmailForResetForgottenPasswordURL: change-password/
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8081